import { CategoryData } from '../types';

export const popkultura: CategoryData = {
  label: 'Pop kultura',
  sentences: [
    { crew: 'Koji fiktivni lik te je najviše nervirao a svi ga vole?', impostor: 'Koji fiktivni lik obožavaš a svi misle da je dosadan?' },
    { crew: 'Koji mim te je nasmejao toliko da si ga slao svima?', impostor: 'Koji mim nikada nisi razumeo a svi se smeju?' },
    { crew: 'Da glumiš u reklami, za šta bi bila?', impostor: 'Da moraš da gledaš jednu reklamu zauvek, koja bi bila?' },
    { crew: 'Koji trend iz 2000-ih bi vratio?', impostor: 'Koji trend iz 2000-ih te i dalje proganja?' },
    { crew: 'Ko je po tebi najjači influenser?', impostor: 'Ko je po tebi najprecenjeniji influenser?' },
    { crew: 'Koji crtani film je oblikovao tvoje detinjstvo?', impostor: 'Koji crtani film si gledao samo jer nije bilo drugog izbora?' },
    { crew: 'Da si na reality show-u, koji bi bio?', impostor: 'Da moraš da gledaš jedan reality show godinu dana, koji bi bio?' },
    { crew: 'Koji celebrity bi bio dobar predsednik?', impostor: 'Koji celebrity bi bio najgori predsednik?' },
    { crew: 'Opiši viralan momenat koji pamtiš.', impostor: 'Opiši internet dramu koja te je fascinirala.' },
    { crew: 'Koja video igra te je najviše emotivno pogodila?', impostor: 'Koja video igra te je najviše iznervirala?' },
    { crew: 'Da si superheroj, koja bi bila tvoja moć?', impostor: 'Da si superzlikovac, koji bi bio tvoj plan?' },
    { crew: 'Koji fiktivni svet bi posetio?', impostor: 'Koji fiktivni svet bi izbegavao po svaku cenu?' },
    { crew: 'Da možeš da izbriñeš jedan žanr pop kulture, koji bi bio?', impostor: 'Da možeš da pojačaš jedan žanr pop kulture, koji bi bio?' },
    { crew: 'Koji je po tebi najbolji video na YouTube-u ikad?', impostor: 'Koji je po tebi najčudniji video na YouTube-u koji si gledao?' },
    { crew: 'Da imaš YouTube kanal, o čemu bi bio?', impostor: 'Da imaš TikTok, kakav sadržaj bi pravio?' },
    { crew: 'Koji fanovi su po tebi najposvećeniji?', impostor: 'Koji fanovi su po tebi najtoksičniji?' },
    { crew: 'Koja je po tebi najjača filmska franšiza?', impostor: 'Koja filmska franšiza je po tebi trebalo da stane na jednom filmu?' },
    { crew: 'Koji celebrity te iznenađuje koliko je pametan?', impostor: 'Koji celebrity te iznenađuje koliko je normalan?' },
    { crew: 'Da organizuješ pop culture quiz, koja bi bila prva kategorija?', impostor: 'Da organizuješ pub quiz, koja bi bila najteža kategorija?' },
    { crew: 'Koji cosplay bi nosio na Comic-Con-u?', impostor: 'Koji cosplay bi te naterao da odeš sa Comic-Con-a?' },
    { crew: 'Da imaš priliku da budeš u jednom TV show-u, kom?', impostor: 'Da moraš da preživiš u jednom TV show-u, kom?' },
    { crew: 'Koji strip bi trebalo da dobije filmsku adaptaciju?', impostor: 'Koja knjiga nikad ne bi trebalo da dobije filmsku adaptaciju?' },
    { crew: 'Koji celebrity par te najviše iznenadio?', impostor: 'Koji celebrity raskid te najviše pogodio?' },
    { crew: 'Koji fiktivni lik bi bio tvoj najbolji drug?', impostor: 'Koji fiktivni lik bi bio tvoj najgori cimer?' },
    { crew: 'Opiši pop culture momenat koji je promenio internet.', impostor: 'Opiši pop culture momenat koji je umro prebrzo.' },
    { crew: 'Da si sudija na takmičenju talenata, šta bi tražio?', impostor: 'Da si učesnik takmičenja talenata, čime bi se takmičio?' },
    { crew: 'Koji anime te je iznenadio koliko je dobar?', impostor: 'Koji anime nikako ne možeš da razumeš zašto ga ljudi vole?' },
    { crew: 'Da se vratiš u bilo koju pop culture dekadu, koja bi bila?', impostor: 'Da moraš da zaboraviš jednu pop culture dekadu, koja bi bila?' },
    { crew: 'Koji je po tebi najjači catchphrase u pop kulturi?', impostor: 'Koji catchphrase te najviše nervira?' },
    { crew: 'Koja igrica je po tebi umetnost?', impostor: 'Koja igrica je po tebi čist gambling prerušen u igru?' },
    { crew: 'Koji je tvoj guilty pleasure u pop kulturi?', impostor: 'Šta u pop kulturi voliš a stidiš se da priznaš?' },
    { crew: 'Da praviš crossover između dva univerzuma, koji bi bili?', impostor: 'Da ukrštaš dva žanra koja ne idu zajedno, koji bi bili?' },
    { crew: 'Koji podcast bi preporučio?', impostor: 'Koji podcast si pokušao da slušaš ali si odustao?' },
    { crew: 'Koji je po tebi najjači debut album?', impostor: 'Koji je po tebi najrazočaravajući povratak neke zvezde?' },
    { crew: 'Koja je po tebi najbolja knjiga pretvorena u film?', impostor: 'Koja je po tebi najgora knjiga pretvorena u film?' },
    { crew: 'Da si u žiriju za Oskara, koji film bi nominovao?', impostor: 'Da si u žiriju za Gremi, koga bi nominovao?' },
    { crew: 'Koji je tvoj omiljeni quote iz filma?', impostor: 'Koji je tvoj omiljeni quote iz serije?' },
    { crew: 'Da praviš top 10 listu pop kulture za ovu godinu, šta bi bilo na vrhu?', impostor: 'Da praviš top 10 listu pop kulture za prošlu deceniju, šta bi bilo na vrhu?' },
    { crew: 'Koja reklamna kampanja ti je ostala u sećanju?', impostor: 'Koja reklamna kampanja te je razočarala?' },
    { crew: 'Da si na naslovnoj strani magazina, koji bi bio naslov?', impostor: 'Da si na naslovnoj strani tabloida, koji bi bio naslov?' },
  ],
  concepts: [
    { crew: 'SpongeBob', impostor: 'Lik iz crtaća koji bi bio loš kuvar' },
    { crew: 'TikTok', impostor: 'Nešto što krade vreme a ne osetiš' },
    { crew: 'Super Mario', impostor: 'Lik koji se bavi pogrešnim poslom' },
    { crew: 'Netflix', impostor: 'Razlog da kažeš "još jedna epizoda"' },
    { crew: 'Pokemon', impostor: 'Sakupljaš ih sve a ne znaš zašto' },
    { crew: 'Stan Lee', impostor: 'Čovek koji se pojavljuje svuda' },
    { crew: 'Mim', impostor: 'Šala sa rokom trajanja od nedelju dana' },
    { crew: 'Beyoncé', impostor: 'Kad je ime dovoljno' },
    { crew: 'Hogwarts', impostor: 'Škola u koju bi svi hteli da idu' },
    { crew: 'Minecraft', impostor: 'Kockice koje su pojele milione sati' },
    { crew: 'Kim Kardashian', impostor: 'Slava bez jasnog razloga' },
    { crew: 'Game of Thrones', impostor: 'Priča koja je iznevrila na kraju' },
    { crew: 'Yoda', impostor: 'Govori čudno, ali svi slušaju' },
    { crew: 'Cosplay', impostor: 'Kad ozbiljno shvatiš fiktivnog lika' },
    { crew: 'Instagram', impostor: 'Život koji izgleda bolje nego što jeste' },
    { crew: 'Darth Vader', impostor: 'Otac koga niko ne bi želeo' },
    { crew: 'Disney', impostor: 'Detinjstvo pretvoreno u industriju' },
    { crew: 'Streaming', impostor: 'Gledaš nekog kako živi umesto tebe' },
    { crew: 'Taylor Swift', impostor: 'Pretvara raskide u platinu' },
    { crew: 'Avengers', impostor: 'Tim koji nikad ne bi radio u kancelariji' },
    { crew: 'Gandalf', impostor: 'Dolazi tačno kad treba' },
    { crew: 'Fortnite', impostor: 'Plesovi koje deca kopiraju' },
    { crew: 'Stranger Things', impostor: 'Nostalgija za decenijom u kojoj nisi živeo' },
    { crew: 'Emoji', impostor: 'Jezik koji koriste svi a niko ne govori' },
    { crew: 'Comic-Con', impostor: 'Gde je biti čudan sasvim normalno' },
    { crew: 'Black Mirror', impostor: 'Tehnologija koja te plaši jer je moguća' },
    { crew: 'Thanos', impostor: 'Kad zlikovac ima smislenu poentu' },
    { crew: 'Squid Game', impostor: 'Dečije igre sa ozbiljnim posledicama' },
    { crew: 'GTA', impostor: 'Svet u kome nema pravila' },
    { crew: 'One Direction', impostor: 'Raskid koji je podelio generaciju' },
    { crew: 'Barbie', impostor: 'Plastika koja je postala ikona' },
    { crew: 'Rick & Morty', impostor: 'Nauka pretvorena u haos' },
    { crew: 'Twitter/X', impostor: 'Mesto gde svi viču a niko ne sluša' },
    { crew: 'The Simpsons', impostor: 'Predvideli budućnost slučajno' },
    { crew: 'Pikachu', impostor: 'Žut i svuda' },
    { crew: 'Oppenheimer', impostor: 'Kad je pamet otišla predaleko' },
    { crew: 'K-pop', impostor: 'Muzika sa vojnom disciplinom' },
    { crew: 'The Walking Dead', impostor: 'Preživljavanje koje je trajalo predugo' },
    { crew: 'Red carpet', impostor: 'Šetnja za koju se spremaš mesecima' },
    { crew: 'Meme lord', impostor: 'Titula koju niko ne traži ali svi poštuju' },
  ],
};
